Noun1 = ""
Noun2 = ""
Noun3 = ""
Noun4 = ""
Adjective1 = ""
Adjective2 = ""
Adjective3 = ""
Adjective4 = ""
Verb1 = ""
Verb2 = ""
Verb3 = ""
Verb4 = ""
print("I was walking to the store one day when I saw a", Adjective1, Noun1 + ". The", Noun1, "was very scary.")